include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    require_trailing_commas: true
